### ISSUE TITLE
Hello World Troubles

### ISSUE THREAD

**Issue by chrisjpatty** [Donorhan/Lemon-JS#16]
Hi, I think this project sounds like a cool idea so I tried to boot up a hello world app using the example code in the docs. I ran into a few snags I thought I'd pass your way. The first problem was that the current npm version at the time of writing: `1.0.0`, didn't seem to be quite inline with the current docs. After importing the necessary classes, it crashed on the first line when trying to access `ProgramLibrary.load`, which isn't a static method on that class. I changed it to `loadFromFile`, which is available, but then it crashed on `Material.create()`, which also was not defined. Changing it to `Material.Create()` did exist and allowed the program to continue, but it then didn't render. Here's copies of my `index.html` and `index.js` files.

# index.html
```html
<html>
  <head>
    <title>Lemon Test</title>
  </head>
  <body>
    <canvas id="simulation" width="800" height="800"></canvas>
    <script type="text/javascript" src='./index.js'></script>
  </body>
</html>
```

# index.js
```js
import {
  ProgramLibrary,
  RenderCanvas,
  Camera,
  Mesh,
  Scene,
  PointLight,
  Geometry,
  Material,
  Color
} from "@dono/lemon-js";

// Use the ProgramLibrary helper to build a shader with lights and texture support
ProgramLibrary.loadFromFile("DefaultShader", "default.vert", "default.frag", [
  "USE_LIGHT",
  "USE_TEXTURE"
]);

// Create a new renderer using HTML identifier
const renderer = new RenderCanvas("simulation");

// A camera to draw the scene
const camera = new Camera();
camera.move(3, 3, 3);
camera.setViewport(0, 0, renderer.getWidth(), renderer.getHeight());

// Create a scene where we can add sprites, lights, objects, …
const scene = new Scene();

// Now we can create our first cube
const cube = new Mesh(
  Geometry.createCube(0.5, 0.5, 0.5),
  Material.Create("default"),
  ProgramLibrary.get("DefaultShader")
);
scene.add(cube);

// A light to see something
const light = new PointLight();
light.setPosition(0, 3, 0);
scene.add(light);

function applicationLoop(deltatime) {
  // Update scene …
  scene.update(deltatime);

  // … then draw it!
  renderer.clear(new Color(30, 30, 30));
  renderer.render(scene, camera);
  renderer.display();
}

applicationLoop()
```

**Comment by Donorhan** [comment]
Hi @chrisjpatty,

Thanks for your feedback! There were some errors in the documentation, so I updated it.

The `applicationloop` function needs to be sent to `requestAnimationFrame` to works properly and you need to enable CORS to load local file (from the `shaders` folder). For now, the best way to try the library is to play with the examples after cloning the repository to understand how it works. 

The library is recent, so I'm trying to simplify all this and allow loading files using `import` and `require` :)

**Comment by chrisjpatty** [comment]
Thanks! I'll give that a try!
